-- VHDL Entity ece411.way.symbol
--
-- Created:
--          by - adalton2.ews (gelib-057-16.ews.illinois.edu)
--          at - 00:16:38 02/20/14
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY way IS
   PORT( 
      CacheWrite : IN     std_logic;
      DataIn     : IN     LC3b_oword;
      DirtyIn    : IN     std_logic;
      Index      : IN     LC3b_c_index;
      RESET_L    : IN     std_logic;
      TagIn      : IN     LC3B_C_TAG;
      DataOut    : OUT    LC3b_oword;
      DirtyOut   : OUT    std_logic;
      TagOut     : OUT    LC3B_C_TAG;
      ValidOut   : OUT    std_logic
   );

-- Declarations

END way ;

--
-- VHDL Architecture ece411.way.struct
--
-- Created:
--          by - adalton2.ews (gelib-057-16.ews.illinois.edu)
--          at - 00:16:38 02/20/14
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;


ARCHITECTURE struct OF way IS

   -- Architecture declarations

   -- Internal signal declarations


   -- Component Declarations
   COMPONENT DataArray
   PORT (
      DataIn    : IN     LC3b_oword;
      DataWrite : IN     std_logic;
      Index     : IN     LC3b_c_index;
      RESET_L   : IN     std_logic;
      DataOut   : OUT    LC3b_oword
   );
   END COMPONENT;
   COMPONENT DirtyArray
   PORT (
      DirtyIn    : IN     std_logic;
      DirtyWrite : IN     std_logic;
      Index      : IN     LC3b_c_index;
      RESET_L    : IN     std_logic;
      DirtyOut   : OUT    std_logic
   );
   END COMPONENT;
   COMPONENT TagArray
   PORT (
      Index    : IN     LC3b_c_index;
      RESET_L  : IN     std_logic;
      TagIn    : IN     LC3B_C_TAG;
      TagWrite : IN     std_logic;
      TagOut   : OUT    LC3B_C_TAG
   );
   END COMPONENT;
   COMPONENT ValidArray
   PORT (
      Index      : IN     LC3b_c_index;
      RESET_L    : IN     std_logic;
      ValidWrite : IN     std_logic;
      ValidOut   : OUT    std_logic
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : DataArray USE ENTITY ece411.DataArray;
   FOR ALL : DirtyArray USE ENTITY ece411.DirtyArray;
   FOR ALL : TagArray USE ENTITY ece411.TagArray;
   FOR ALL : ValidArray USE ENTITY ece411.ValidArray;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   WayData : DataArray
      PORT MAP (
         RESET_L   => RESET_L,
         DataWrite => CacheWrite,
         Index     => Index,
         DataIn    => DataIn,
         DataOut   => DataOut
      );
   WayDirty : DirtyArray
      PORT MAP (
         RESET_L    => RESET_L,
         DirtyWrite => CacheWrite,
         Index      => Index,
         DirtyIn    => DirtyIn,
         DirtyOut   => DirtyOut
      );
   WayTag : TagArray
      PORT MAP (
         RESET_L  => RESET_L,
         TagWrite => CacheWrite,
         Index    => Index,
         TagIn    => TagIn,
         TagOut   => TagOut
      );
   WayValid : ValidArray
      PORT MAP (
         RESET_L    => RESET_L,
         ValidWrite => CacheWrite,
         Index      => Index,
         ValidOut   => ValidOut
      );

END struct;
